export declare enum UserRole {
    CUSTOMER = "CUSTOMER",
    FIXER = "FIXER",
    ADMIN = "ADMIN",
    SUPER_ADMIN = "SUPER_ADMIN"
}
export declare enum UserStatus {
    ACTIVE = "ACTIVE",
    BLOCKED = "BLOCKED",
    DEACTIVATED = "DEACTIVATED",
    PENDING_VERIFICATION = "PENDING_VERIFICATION"
}
export declare enum FixerVerificationStatus {
    REGISTERED = "REGISTERED",
    DOCUMENT_SUBMITTED = "DOCUMENT_SUBMITTED",
    UNDER_REVIEW = "UNDER_REVIEW",
    VERIFIED = "VERIFIED",
    REJECTED = "REJECTED",
    BLOCKED = "BLOCKED"
}
export declare enum RequestStatus {
    OPEN = "OPEN",
    QUOTED = "QUOTED",
    CUSTOMER_ACCEPTED = "CUSTOMER_ACCEPTED",
    ASSIGNED = "ASSIGNED",
    FIXER_ON_THE_WAY = "FIXER_ON_THE_WAY",
    DEVICE_RECEIVED = "DEVICE_RECEIVED",
    DIAGNOSING = "DIAGNOSING",
    REPAIR_IN_PROGRESS = "REPAIR_IN_PROGRESS",
    READY_FOR_DELIVERY = "READY_FOR_DELIVERY",
    COMPLETED = "COMPLETED",
    REVIEWED = "REVIEWED",
    CANCELLED = "CANCELLED",
    DISPUTED = "DISPUTED"
}
export declare enum QuoteStatus {
    DRAFT = "DRAFT",
    SUBMITTED = "SUBMITTED",
    VIEWED = "VIEWED",
    ACCEPTED = "ACCEPTED",
    REJECTED = "REJECTED",
    WITHDRAWN = "WITHDRAWN",
    EXPIRED = "EXPIRED"
}
export declare enum JobStatus {
    ASSIGNED = "ASSIGNED",
    FIXER_ON_THE_WAY = "FIXER_ON_THE_WAY",
    DEVICE_RECEIVED = "DEVICE_RECEIVED",
    DIAGNOSING = "DIAGNOSING",
    REPAIR_IN_PROGRESS = "REPAIR_IN_PROGRESS",
    READY_FOR_DELIVERY = "READY_FOR_DELIVERY",
    COMPLETED = "COMPLETED",
    CANCELLED = "CANCELLED",
    DISPUTED = "DISPUTED"
}
export declare enum UrgencyLevel {
    LOW = "LOW",
    MEDIUM = "MEDIUM",
    HIGH = "HIGH",
    EMERGENCY = "EMERGENCY"
}
export declare enum NotificationType {
    REQUEST_CREATED = "REQUEST_CREATED",
    QUOTE_RECEIVED = "QUOTE_RECEIVED",
    QUOTE_ACCEPTED = "QUOTE_ACCEPTED",
    QUOTE_REJECTED = "QUOTE_REJECTED",
    NEW_MESSAGE = "NEW_MESSAGE",
    JOB_ASSIGNED = "JOB_ASSIGNED",
    JOB_STATUS_CHANGED = "JOB_STATUS_CHANGED",
    REPAIR_COMPLETED = "REPAIR_COMPLETED",
    REVIEW_REMINDER = "REVIEW_REMINDER",
    REVIEW_RECEIVED = "REVIEW_RECEIVED",
    COMPLAINT_UPDATED = "COMPLAINT_UPDATED",
    VERIFICATION_APPROVED = "VERIFICATION_APPROVED",
    VERIFICATION_REJECTED = "VERIFICATION_REJECTED",
    ACCOUNT_BLOCKED = "ACCOUNT_BLOCKED",
    NEW_MATCHING_REQUEST = "NEW_MATCHING_REQUEST"
}
export declare enum NotificationChannel {
    IN_APP = "IN_APP",
    PUSH = "PUSH",
    EMAIL = "EMAIL",
    SMS = "SMS"
}
export declare enum ComplaintStatus {
    OPEN = "OPEN",
    UNDER_REVIEW = "UNDER_REVIEW",
    WAITING_FOR_INFORMATION = "WAITING_FOR_INFORMATION",
    RESOLVED = "RESOLVED",
    REJECTED = "REJECTED",
    CLOSED = "CLOSED"
}
export declare enum ComplaintReason {
    FIXER_DID_NOT_ARRIVE = "FIXER_DID_NOT_ARRIVE",
    POOR_SERVICE = "POOR_SERVICE",
    OVERCHARGING = "OVERCHARGING",
    DEVICE_DAMAGE = "DEVICE_DAMAGE",
    WARRANTY_ISSUE = "WARRANTY_ISSUE",
    UNPROFESSIONAL_BEHAVIOR = "UNPROFESSIONAL_BEHAVIOR",
    SUSPECTED_FRAUD = "SUSPECTED_FRAUD",
    FAKE_CUSTOMER = "FAKE_CUSTOMER",
    CUSTOMER_NO_SHOW = "CUSTOMER_NO_SHOW",
    ABUSIVE_BEHAVIOR = "ABUSIVE_BEHAVIOR",
    PAYMENT_DISPUTE = "PAYMENT_DISPUTE",
    FALSE_COMPLAINT = "FALSE_COMPLAINT"
}
export declare enum DocumentType {
    BUSINESS_LICENSE = "BUSINESS_LICENSE",
    ID_PROOF = "ID_PROOF",
    GST_CERTIFICATE = "GST_CERTIFICATE",
    ADDRESS_PROOF = "ADDRESS_PROOF",
    BANK_STATEMENT = "BANK_STATEMENT",
    OTHER = "OTHER"
}
export declare enum DocumentStatus {
    PENDING = "PENDING",
    APPROVED = "APPROVED",
    REJECTED = "REJECTED"
}
export declare enum AddressType {
    HOME = "HOME",
    WORK = "WORK",
    OTHER = "OTHER"
}
export declare enum MediaType {
    PHOTO = "PHOTO",
    VIDEO = "VIDEO"
}
export declare enum ReviewStatus {
    VISIBLE = "VISIBLE",
    HIDDEN = "HIDDEN"
}
export declare enum ServiceAreaType {
    PINCODE = "PINCODE",
    CITY = "CITY",
    RADIUS = "RADIUS"
}
export declare enum AuditAction {
    USER_LOGIN = "USER_LOGIN",
    USER_LOGOUT = "USER_LOGOUT",
    USER_SIGNUP = "USER_SIGNUP",
    PASSWORD_RESET = "PASSWORD_RESET",
    ACCOUNT_BLOCKED = "ACCOUNT_BLOCKED",
    ACCOUNT_UNBLOCKED = "ACCOUNT_UNBLOCKED",
    ACCOUNT_DEACTIVATED = "ACCOUNT_DEACTIVATED",
    FIXER_VERIFICATION_SUBMITTED = "FIXER_VERIFICATION_SUBMITTED",
    FIXER_VERIFIED = "FIXER_VERIFIED",
    FIXER_REJECTED = "FIXER_REJECTED",
    QUOTE_ACCEPTED = "QUOTE_ACCEPTED",
    QUOTE_REJECTED = "QUOTE_REJECTED",
    JOB_STATUS_CHANGED = "JOB_STATUS_CHANGED",
    JOB_CANCELLED = "JOB_CANCELLED",
    REVIEW_HIDDEN = "REVIEW_HIDDEN",
    REVIEW_RESTORED = "REVIEW_RESTORED",
    COMPLAINT_STATUS_CHANGED = "COMPLAINT_STATUS_CHANGED",
    DISPUTE_RESOLVED = "DISPUTE_RESOLVED",
    ADMIN_CREATED = "ADMIN_CREATED",
    SENSITIVE_DATA_ACCESSED = "SENSITIVE_DATA_ACCESSED"
}
//# sourceMappingURL=enums.d.ts.map