// ============================================================
// Fix Me — Core Enumerations
// ============================================================

export enum UserRole {
  CUSTOMER = 'CUSTOMER',
  FIXER = 'FIXER',
  FIXER_MEMBER = 'FIXER_MEMBER',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum QuoteRevisionStatus {
  NONE = 'NONE',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  DECLINED = 'DECLINED',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  BLOCKED = 'BLOCKED',
  DEACTIVATED = 'DEACTIVATED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}

export enum FixerVerificationStatus {
  REGISTERED = 'REGISTERED',
  DOCUMENT_SUBMITTED = 'DOCUMENT_SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  BLOCKED = 'BLOCKED',
}

export enum RequestStatus {
  OPEN = 'OPEN',
  QUOTED = 'QUOTED',
  CUSTOMER_ACCEPTED = 'CUSTOMER_ACCEPTED',
  ASSIGNED = 'ASSIGNED',
  FIXER_ON_THE_WAY = 'FIXER_ON_THE_WAY',
  DEVICE_RECEIVED = 'DEVICE_RECEIVED',
  DIAGNOSING = 'DIAGNOSING',
  REPAIR_IN_PROGRESS = 'REPAIR_IN_PROGRESS',
  READY_FOR_DELIVERY = 'READY_FOR_DELIVERY',
  COMPLETED = 'COMPLETED',
  REVIEWED = 'REVIEWED',
  CANCELLED = 'CANCELLED',
  DISPUTED = 'DISPUTED',
}

export enum QuoteStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  VIEWED = 'VIEWED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
  EXPIRED = 'EXPIRED',
}

export enum JobStatus {
  ASSIGNED = 'ASSIGNED',
  FIXER_ON_THE_WAY = 'FIXER_ON_THE_WAY',
  DEVICE_RECEIVED = 'DEVICE_RECEIVED',
  DIAGNOSING = 'DIAGNOSING',
  REPAIR_IN_PROGRESS = 'REPAIR_IN_PROGRESS',
  READY_FOR_DELIVERY = 'READY_FOR_DELIVERY',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  DISPUTED = 'DISPUTED',
}

export enum UrgencyLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  EMERGENCY = 'EMERGENCY',
}

export enum NotificationType {
  REQUEST_CREATED = 'REQUEST_CREATED',
  QUOTE_RECEIVED = 'QUOTE_RECEIVED',
  QUOTE_ACCEPTED = 'QUOTE_ACCEPTED',
  QUOTE_REJECTED = 'QUOTE_REJECTED',
  NEW_MESSAGE = 'NEW_MESSAGE',
  JOB_ASSIGNED = 'JOB_ASSIGNED',
  JOB_STATUS_CHANGED = 'JOB_STATUS_CHANGED',
  REPAIR_COMPLETED = 'REPAIR_COMPLETED',
  REVIEW_REMINDER = 'REVIEW_REMINDER',
  REVIEW_RECEIVED = 'REVIEW_RECEIVED',
  COMPLAINT_UPDATED = 'COMPLAINT_UPDATED',
  VERIFICATION_APPROVED = 'VERIFICATION_APPROVED',
  VERIFICATION_REJECTED = 'VERIFICATION_REJECTED',
  ACCOUNT_BLOCKED = 'ACCOUNT_BLOCKED',
  NEW_MATCHING_REQUEST = 'NEW_MATCHING_REQUEST',
}

export enum NotificationChannel {
  IN_APP = 'IN_APP',
  PUSH = 'PUSH',
  EMAIL = 'EMAIL',
  SMS = 'SMS',
}

export enum ComplaintStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  WAITING_FOR_INFORMATION = 'WAITING_FOR_INFORMATION',
  RESOLVED = 'RESOLVED',
  REJECTED = 'REJECTED',
  CLOSED = 'CLOSED',
}

export enum ComplaintReason {
  // Customer reasons
  FIXER_DID_NOT_ARRIVE = 'FIXER_DID_NOT_ARRIVE',
  POOR_SERVICE = 'POOR_SERVICE',
  OVERCHARGING = 'OVERCHARGING',
  DEVICE_DAMAGE = 'DEVICE_DAMAGE',
  WARRANTY_ISSUE = 'WARRANTY_ISSUE',
  UNPROFESSIONAL_BEHAVIOR = 'UNPROFESSIONAL_BEHAVIOR',
  SUSPECTED_FRAUD = 'SUSPECTED_FRAUD',
  // Fixer reasons
  FAKE_CUSTOMER = 'FAKE_CUSTOMER',
  CUSTOMER_NO_SHOW = 'CUSTOMER_NO_SHOW',
  ABUSIVE_BEHAVIOR = 'ABUSIVE_BEHAVIOR',
  PAYMENT_DISPUTE = 'PAYMENT_DISPUTE',
  FALSE_COMPLAINT = 'FALSE_COMPLAINT',
}

export enum DocumentType {
  BUSINESS_LICENSE = 'BUSINESS_LICENSE',
  ID_PROOF = 'ID_PROOF',
  GST_CERTIFICATE = 'GST_CERTIFICATE',
  ADDRESS_PROOF = 'ADDRESS_PROOF',
  BANK_STATEMENT = 'BANK_STATEMENT',
  OTHER = 'OTHER',
}

export enum DocumentStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum AddressType {
  HOME = 'HOME',
  WORK = 'WORK',
  OTHER = 'OTHER',
}

export enum MediaType {
  PHOTO = 'PHOTO',
  VIDEO = 'VIDEO',
}

export enum ReviewStatus {
  VISIBLE = 'VISIBLE',
  HIDDEN = 'HIDDEN',
}

export enum ServiceAreaType {
  PINCODE = 'PINCODE',
  CITY = 'CITY',
  RADIUS = 'RADIUS',
}

export enum AuditAction {
  // Auth
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_SIGNUP = 'USER_SIGNUP',
  PASSWORD_RESET = 'PASSWORD_RESET',
  // Account management
  ACCOUNT_BLOCKED = 'ACCOUNT_BLOCKED',
  ACCOUNT_UNBLOCKED = 'ACCOUNT_UNBLOCKED',
  ACCOUNT_DEACTIVATED = 'ACCOUNT_DEACTIVATED',
  // Fixer verification
  FIXER_VERIFICATION_SUBMITTED = 'FIXER_VERIFICATION_SUBMITTED',
  FIXER_VERIFIED = 'FIXER_VERIFIED',
  FIXER_REJECTED = 'FIXER_REJECTED',
  // Quote actions
  QUOTE_ACCEPTED = 'QUOTE_ACCEPTED',
  QUOTE_REJECTED = 'QUOTE_REJECTED',
  // Job actions
  JOB_STATUS_CHANGED = 'JOB_STATUS_CHANGED',
  JOB_CANCELLED = 'JOB_CANCELLED',
  // Review actions
  REVIEW_HIDDEN = 'REVIEW_HIDDEN',
  REVIEW_RESTORED = 'REVIEW_RESTORED',
  // Complaint actions
  COMPLAINT_STATUS_CHANGED = 'COMPLAINT_STATUS_CHANGED',
  DISPUTE_RESOLVED = 'DISPUTE_RESOLVED',
  // Admin
  ADMIN_CREATED = 'ADMIN_CREATED',
  SENSITIVE_DATA_ACCESSED = 'SENSITIVE_DATA_ACCESSED',
}
